name: 'Create Issues'
description: 'Creates new issues from a glob of markdown templates with frontmatter, optionally adding them to projects.'
author: '@jayalfredprufrock'

branding:
  icon: alert-circle
  color: blue

inputs:
  templatePath:
    description: 'Path or glob expression to templates. File names should be unique across directories.'
    required: false
    default: '.github/issues/**/*.md'

outputs:
  issues:
    description: 'Map of template names (excluding file extension) containing issue/project info.'

runs:
  using: node20
  main: dist/index.js
