name: Create Issues
description: Creates new issues from a glob of markdown templates with frontmatter, optionally adding them to projects.
author: '@jayalfredprufrock'

branding:
  icon: alert-circle
  color: blue

inputs:
  template-path:
    description: Path or glob expression to templates. File names should be unique across directories.
    default: .github/issues/**/*.md
    required: false

  follow-symbolic-links:
    description: Indicates whether to follow symbolic links when globbing templates.
    default: true
    required: false

  owner:
    description: The owner of the repo to create issues in if different than the context repo owner. Can be overridden in frontmatter with 'owner'
    required: false

  repo:
    description: The the repo name to create issues in if different than the context repo. Can be overridden in frontmatter with 'repo'
    required: false

  github-token:
    description: GitHub token or PAT with permissions to create issues and projects in the specified repos.
    default: ${{ github.token }}
    required: false

  project-owner:
    description: The owner of the project if different than the context repo owner. Can be overridden in frontmatter with 'projectOwner'
    required: false

  project-number:
    description: The number of the project (found in the url) if the issue should be added to the project. Can be overridden in frontmatter with 'projectNumber'
    required: false

  project-github-token:
    description: GitHub PAT token to use solely for adding issues to projects. Will use 'github-token' input if not present.
    required: false
    
outputs:
  issues:
    description: Map of template names (excluding file extension) containing issue/project info. Use fromJSON to parse output string. }})

runs:
  using: node20
  main: dist/index.js
