name: Create Issues
description: Creates new issues from a glob of markdown templates with frontmatter, optionally adding them to projects.
author: '@jayalfredprufrock'

branding:
  icon: alert-circle
  color: blue

inputs:
  template-path:
    description: Path or glob expression to templates. File names should be unique across directories.
    default: .github/issues/**/*.md

  follow-symbolic-links:
    description: Indicates whether to follow symbolic links when globbing templates
    default: true

  github-token:
    description: GitHub token or PAT with permissions to create issues and projects in the specified repos
    default: ${{ github.token }}

outputs:
  issues:
    description: Map of template names (excluding file extension) containing issue/project info.

runs:
  using: node20
  main: dist/index.js
