name: Test Action

on:
  workflow_dispatch:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    permissions:
      issues: write 

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: npm

      - name: Install dependencies
        run: npm ci --omit=dev
            
      - name: Compile and bundle action
        run: npm run build

      - name: Create/Update Test Issues
        uses: ./index.cjs
        with:
          project-github-token: ${{ secrets.GH_TOKEN_PROJECT_WRITE }}
          project-number: 1


